MachineCafeIHM/MachineCafeIHM/Models/ChoixBoissonApiPoco.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MachineCafeIHM.Models
{
    public class ChoixBoissonApiPoco
    {
        public string BoissonType { get; set; }
        public int SucreQuantite { get; set; }
        public bool CustomMug { get; set; }
        public string CodeBadge { get; set; }
    }
    public class ChoixBoissonListApiPoco : List<ChoixBoissonApiPoco>
    {

    }
}

MachineCafeIHM/MachineCafeIHM/Controllers/MachineCafeController.cs
using MachineCafeIHM.ApiWrapper;
using MachineCafeIHM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MachineCafeIHM.Controllers
{
    public class MachineCafeController : Controller
    {
        // GET: ChoixBoisson
        public ActionResult ChoixBoisson()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChoixBoisson(string badgecode)
        {
            return View();
        }
        [HttpPost]
        public ActionResult DemanderBoisson(ChoixBoissonApiPoco choix)
        {

            MachineCafeApiWrapper machineCafeApiWrapper = new MachineCafeApiWrapper("http://localhost:60351/api/MachineCafe/", "", "");
            string message = string.Empty;
            machineCafeApiWrapper.DemanderBoisson(choix, out message);

            if (string.IsNullOrEmpty(message))
                message = "Votre boisson est servi.";

            ViewBag.message = message;
           
            return View("ChoixBoisson");
        }
        public ActionResult ChoixBoissonList(string badgecode)
        {

            MachineCafeApiWrapper machineCafeApiWrapper = new MachineCafeApiWrapper("http://localhost:60351/api/MachineCafe/", "", "");
            string message = string.Empty;
            ChoixBoissonListApiPoco choixBoissonList = machineCafeApiWrapper.DemandeBoissonList(badgecode, out message);
            ViewBag.choixList = choixBoissonList;
            return View("ChoixBoisson");
        }
    }
}

MachineCafeIHM/MachineCafeIHM/Views/MachineCafe/ChoixBoisson.cshtml
@{
    /**/

    ViewBag.Title = "ChoixBoisson";
    MachineCafeIHM.Models.ChoixBoissonListApiPoco choixList = ViewBag.choixList;
    string message = ViewBag.message;

}



<div class="panel panel-primary">
    <!-- Default panel contents -->
    <div class="panel-heading">Machine a café</div>
    <div class="panel-body">

        @if (!string.IsNullOrEmpty(message))
    {
        <span style="color:red">@message</span>
}

        @if (choixList != null && choixList.Count > 0)
    {
            <a href='@Url.Action("ChoixBoisson","MachineCafe")'>Réinitialiser ma recherche par badge</a>
        @Html.Partial("ChoixBoissonList", choixList)
}
else
{
    using (Html.BeginForm("ChoixBoissonList", "MachineCafe"))
    {
        <div class="panel panel-primary">
            <div class="panel-body">
                <span>Vos anciens choix badge.</span>
                <div class="row">
                    <div class="col-md-3">
                        Code de badge :
                    </div>
                    <input type="text" name="badgecode" id="badgecode" />
                </div>
                <div class="row" align="right" style="padding:5px">
                    <button type="submit" id="btn_choixboisson" class="btn btn-primary">Chercher</button>
                </div>
                </div>
            </div>

}
}
        @using (Html.BeginForm("DemanderBoisson", "MachineCafe"))
    {
        <div class="panel panel-primary">
            <div class="panel-body">
                <span>Vous pouvez choisir un nouveau configuration de boisson.</span>
                <div class="row">
                    <div class="col-md-3">
                        <label>
                            Boisson :
                        </label>
                    </div>
                    <select name="BoissonType" class="selectpicker">
                        <option value="Cafe">Cafe</option>
                        <option value="Chocolat">Chocolat</option>
                        <option value="Thé">Thé</option>
                    </select>

                </div>
                <div class="row">
                    <div class="col-md-3">
                        <label>
                            Quantité de sucre :
                        </label>
                    </div>
                    <input type="number" value="0" name="SucreQuantite" min="0" max="5">
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <label>Votre propre mug</label>
                    </div>
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">

                </div>
                <div class="row">
                    <div class="col-md-3">
                        <label>Code de badge :</label>
                    </div>
                    <input type="text" name="codebadge" id="badgecode" />
                </div>
                <div align="right">
                    <button type="submit" id="btn_choixboisson" class="btn btn-primary">Demande un nouveau boisson</button>
                </div>
            </div>
        </div>
}
    </div>
            </div>
       

MachineCafeIHM/MachineCafeIHM/Views/MachineCafe/ChoixBoissonList.cshtml
@model MachineCafeIHM.Models.ChoixBoissonListApiPoco
@{
    ViewBag.Title = "ChoixBoissonList";
}


@foreach (MachineCafeIHM.Models.ChoixBoissonApiPoco choix in Model)
{
    <div class="panel panel-primary">
        <div class="panel-body">
            @using (Html.BeginForm("DemanderBoisson", "MachineCafe"))
            {
                <input type="hidden" name="BoissonType" value="@choix.BoissonType" />
                <input type="hidden" name="CodeBadge" value="@choix.CodeBadge" />
                <input type="hidden" name="CustomMug" value="@choix.CustomMug" />
                <input type="hidden" name="SucreQuantite" value="@choix.SucreQuantite" />
                <span>Merci de choisisser votre boisson.</span>
                <div class="row">
                    <div class="col-md-3">                        
                            @if (choix.BoissonType == "0")
                            {
                                <label>
                                    Boisson: Café
                                </label>
                            }
                            @if (choix.BoissonType == "1")
                            {
                                <label>Boisson: Chocolat</label>
                            }
                            @if (choix.BoissonType == "2")
                            {
                                <label>Boisson: Chocolat</label>   
                            }
                        
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-3">
                        <label>
                            Quantité de sucre : @choix.SucreQuantite
                        </label>
                    </div>
                </div>
                <div class="row">
            <div class="col-md-3">
                @if (choix.CustomMug)
                {
                    <label>Votre propre mug : Oui</label>
                }
                else
                {
                        <label>Votre propre mug : Non</label>
                }
            </div>
        </div>
                <div align="right">
                    <button type="submit" id="btn_choixboisson" class="btn btn-primary">Demande votre boisson</button>
                </div>
            }
        </div>
    </div>
}

MachineCafeIHM/MachineCafeIHM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
     @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
  
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Machine café Demo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>